import type { Config } from 'tailwindcss';

export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: '#E20074',
        'brand-dark': '#1A1A2E',
        'on-surface-variant': '#e3bdc5',
        'surface-container': '#1d2021',
        'inverse-on-surface': '#2e3132',
        'outline': '#aa8890',
        'on-primary-fixed': '#3f001c',
        'on-primary': '#650030',
        'tertiary-fixed-dim': '#bec6e3',
        'surface-variant': '#323536',
        'inverse-primary': '#ba005e',
        'on-tertiary-container': '#fdfaff',
        'surface-container-high': '#282a2b',
        'on-primary-fixed-variant': '#8e0047',
        'surface': '#111415',
        'on-secondary-container': '#b1b7d6',
        'primary-container': '#e20074',
        'on-tertiary': '#283046',
        'primary': '#ffb1c6',
        'secondary': '#bfc5e4',
        'secondary-fixed-dim': '#bfc5e4',
        'outline-variant': '#5b3f46',
        'on-secondary': '#292f48',
        'error-container': '#93000a',
        'inverse-surface': '#e1e3e4',
        'on-background': '#e1e3e4',
        'on-error': '#690005',
        'primary-fixed': '#ffd9e1',
        'secondary-container': '#424862',
        'tertiary-fixed': '#dae2ff',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#131b30',
        'surface-bright': '#373a3b',
        'surface-tint': '#ffb1c6',
        'tertiary': '#bec6e3',
        'on-secondary-fixed-variant': '#3f465f',
        'on-primary-container': '#fffbfa',
        'primary-fixed-dim': '#ffb1c6',
        'tertiary-container': '#6b738d',
        'on-secondary-fixed': '#141a32',
        'surface-dim': '#111415',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#191c1d',
        'on-tertiary-fixed-variant': '#3e465e',
        'on-surface': '#e1e3e4',
        'secondary-fixed': '#dce1ff',
        'surface-container-highest': '#323536',
        'surface-container-lowest': '#0c0f10',
        'background': '#111415',
      },
      fontFamily: {
        'manrope':    ['Manrope', 'sans-serif'],
        'body-lg':    ['Manrope', 'sans-serif'],
        'label-lg':   ['Manrope', 'sans-serif'],
        'body-md':    ['Manrope', 'sans-serif'],
        'headline-lg':['Manrope', 'sans-serif'],
        'headline-md':['Manrope', 'sans-serif'],
        'body-sm':    ['Manrope', 'sans-serif'],
        'headline-sm':['Manrope', 'sans-serif'],
        'label-md':   ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-lg':     ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'label-lg':    ['14px', { lineHeight: '1.2',  letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md':     ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2',  fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3',  fontWeight: '600' }],
        'body-sm':     ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4',  fontWeight: '600' }],
        'label-md':    ['12px', { lineHeight: '1.2',  letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'unit':              '8px',
        'stack-sm':          '8px',
        'stack-lg':          '24px',
        'gutter':            '16px',
        'container-padding': '20px',
        'stack-md':          '16px',
      },
    },
  },
  plugins: [],
} satisfies Config;
